name: Build Gamdl GUI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Gamdl GUI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Install system dependencies on MacOS
      - name: Install system dependencies on MacOS
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install qt
          echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> $GITHUB_ENV

      # Step 4: Add Python Scripts to PATH (Windows)
      - name: Add Python Scripts to PATH
        if: runner.os == 'Windows'
        run: echo "${{ env.pythonLocation }}\\Scripts" >> $GITHUB_PATH

      # Step 5: Upgrade Python Build Tools
      - name: Upgrade Python Build Tools
        run: |
          python -m pip install --upgrade pip setuptools wheel

      # Step 6: Install Compatibility Dependencies for PyQt5
      - name: Install Compatibility Dependencies for PyQt5
        run: |
          pip install sipbuild PyQt5-sip==12.11.1

      # Step 7: Install Python Dependencies
      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt

      # Step 8: Install PyInstaller
      - name: Install PyInstaller
        run: python -m pip install pyinstaller

      # Step 9: Build the application with PyInstaller
      - name: Build Application
        run: |
          pyinstaller --onefile --noconsole --add-data "bin:bin" gamdl_gui/main.py
        env:
          PYTHONPATH: ${{ runner.workspace }}

      # Step 10: Upload build artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gamdl-gui-${{ matrix.os }}
          path: dist/*